# Generated by Django 4.0.1 on 2022-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_date_task_date_rename_heading_task_heading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='details',
            new_name='Details',
        ),
        migrations.AlterField(
            model_name='task',
            name='is_deleted',
            field=models.CharField(default='n', max_length=2),
        ),
    ]
